default: &default
  host: db
  username: postgres
  password: password
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: adventure-time_development

test:
  <<: *default
  database: adventure-time_test
