name: Test
on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest

    env:
        RAILS_ENV: test
        DATABASE_URL: "postgresql://root:password@localhost/adventure-time_test?pool=5"
        TZ: "/usr/share/zoneinfo/America/New_York"
        COV: '1'
        BUNDLER_PATH: vendor/bundle
        BUNDLER_JOBS: 4
        YARN_CACHE_FOLDER: ~/.cache/yarn

    services:
      postgres:
        image: postgres:14.12-alpine
        env:
          POSTGRES_USER: root
          POSTGRES_DB: adventure-time_test
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        # Add a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up ruby 2.7.2
        uses: ruby/setup-ruby@v1

      - name: Set up Ruby dependencies
        run: |
          gem update bundler
          bundle install

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '14.17.0'
          cache: 'yarn'

      - run: node --version
      - run: yarn --version

      - name: Install js dependencies
        run: |
          yarn install --pure-lockfile

      - name: Database setup
        run: bundle exec rake db:migrate --trace

      - name: Run specs
        run: bundle exec rspec
